#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := dpos

include $(IDF_PATH)/make/project.mk
EXTRA_CPPFLAGS = -D F_XTENSA
